
let query = `SELECT STUDENT.FIRST_NAME,STUDENT.LAST_NAME,STUDENT.CITY,  DATE_FORMAT(FROM_DAYS(DATEDIFF('2020-01-01',STUDENT.DOB)), '%Y')+1 AS AGE
FROM STUDENT INNER JOIN COURSE ON COURSE.STUD_ID = STUD_ID WHERE COURSE.COURSE_NAME = 'PHYSICS' OR COURSE.COURSE_NAME = 'MATHS' GROUP BY STUDENT.STUD_ID`;